### PR TITLE
add url

### PR DESCRIPTION
**Pull request by wingkicwk**
there are lots of formatting but essentially the only change is the url from `/` to `/api/savings`

### CODE REVIEW

**Comment by yiyuangeng** [comment]
May I ask why you remove the validator.js and put all functions in one js file?

**Comment by wingkicwk** [comment]
just lazy to add imports between files because seems complicated to do so in javascript :/

**Comment by wingkicwk** [comment]
but I agree separate is better

**Comment by wingkicwk** [comment]
close and url will be update in another pr with new linter

**Pull request closed without merging**
